In [3]:
import pandas as pd
import numpy as np

In [4]:
Customers = pd.read_csv('customers.csv')
order_item = pd.read_csv('order_items.csv')
order = pd.read_csv("orders.csv") 
Product_detail = pd.read_csv("products.csv")

In [5]:
Customers.head(1)

,customer_id,full_name,email,city,signup_date,age,gender,loyalty_tier
0,C000001,Sneha Sharma,sneha.sharma1@email.com,Chennai,2023-01-16,32,M,Silver

In [6]:
order_item.head(1)

      item_id    order_id product_id  quantity  unit_price  total_price
0  IT00000001  ORD0000001      P0070         1     6767.57      6767.57

In [7]:
order.head(1)

,order_id,customer_id,order_date,status,payment_method,total_amount,delivery_days,discount_applied
0,ORD0000001,C004260,2024-12-19 06:08:54,delivered,COD,3995.84,2,0.0

In [8]:
Product_detail.head(1)

  product_id      product_name     category    price  stock_quantity
0      P0001  Wireless Earbuds  Electronics  5771.87              12

In [9]:
Merge = pd.merge(Customers,order,on = "customer_id" )

In [10]:
Merge.head(1)

,customer_id,full_name,email,city,signup_date,age,gender,loyalty_tier,order_id,order_date,status,payment_method,total_amount,delivery_days,discount_applied
0,C000001,Sneha Sharma,sneha.sharma1@email.com,Chennai,2023-01-16,32,M,Silver,ORD0012218,2023-04-16 17:40:44,delivered,UPI,3034.03,5,0.0

In [11]:
Merge2 = pd.merge(order_item,Product_detail,on="product_id")

In [12]:
df = pd.merge(Merge,Merge2,on="order_id")

In [13]:
df.head(1)

,customer_id,full_name,email,city,signup_date,age,gender,loyalty_tier,order_id,order_date,...,discount_applied,item_id,product_id,quantity,unit_price,total_price,product_name,category,price,stock_quantity
0,C000001,Sneha Sharma,sneha.sharma1@email.com,Chennai,2023-01-16,32,M,Silver,ORD0012218,2023-04-16 17:40:44,...,0.0,IT00023596,P0014,2,7119.34,14238.68,Track Pants,Clothing,6840.33,81

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 964870 entries, 0 to 964869
Data columns (total 24 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   customer_id       964870 non-null  str
 1   full_name         964870 non-null  str
 2   email             964870 non-null  str
 3   city              964870 non-null  str
 4   signup_date       964870 non-null  str
 5   age               964870 non-null  int64
 6   gender            964870 non-null  str
 7   loyalty_tier      964870 non-null  str
 8   order_id          964870 non-null  str
 9   order_date        964870 non-null  str
 10  status            964870 non-null  str
 11  payment_method    964870 non-null  str
 12  total_amount      964870 non-null  float64
 13  delivery_days     964870 non-null  int64
 14  discount_applied  964870 non-null  float64
 15  item_id           964870 non-null  str
 16  product_id        964870 non-null  str
 17  quantity          964870 non-null  int64
 18  unit_price        964870 non-null  float64
 19  total_price       964870 non-null  float64
 20  product_name      964870 non-null  str
 21  category          964870 non-null  str
 22  price             964870 non-null  float64
 23  stock_quantity    964870 non-null  int64
dtypes: float64(5), int64(4), str(15)
memory usage: 176.7 MB

In [15]:
df['signup_date'] = pd.to_datetime(df['signup_date'])

In [16]:
df['signup_Month'] = df["signup_date"].dt.month_name()

In [17]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [18]:
df['order_month'] = df['order_date'].dt.month_name()

In [19]:
df['order_year'] = df['order_date'].dt.year

In [20]:
df.isnull().sum()

customer_id         0
full_name           0
email               0
city                0
signup_date         0
age                 0
gender              0
loyalty_tier        0
order_id            0
order_date          0
status              0
payment_method      0
total_amount        0
delivery_days       0
discount_applied    0
item_id             0
product_id          0
quantity            0
unit_price          0
total_price         0
product_name        0
category            0
price               0
stock_quantity      0
signup_Month        0
order_month         0
order_year          0
dtype: int64

In [21]:
df[['total_amount','unit_price','quantity']].describe()

        total_amount     unit_price       quantity
count  964870.000000  964870.000000  964870.000000
mean     6049.104335    4688.770009       2.500945
std      3440.438993    2493.047694       1.118352
min        99.010000     243.530000       1.000000
25%      3060.902500    2283.270000       1.000000
50%      6053.915000    5123.455000       3.000000
75%      9030.230000    6657.315000       4.000000
max     11999.950000    9871.740000       4.000000

In [22]:
(df['unit_price']*df['quantity']) == df['total_price']

0         True
1         True
2         True
3         True
4         True
          ...
964865    True
964866    True
964867    True
964868    True
964869    True
Length: 964870, dtype: bool

In [23]:
df[["total_price","total_amount","order_id","quantity" ,"product_id",]]

        total_price  total_amount    order_id  quantity product_id
0          14238.68       3034.03  ORD0012218         2      P0014
1           5160.83       3034.03  ORD0012218         1      P0011
2           2917.40       3034.03  ORD0012218         4      P0028
3          16034.28       3034.03  ORD0012218         2      P0077
4           1156.78       8253.95  ORD0124146         2      P0028
...             ...           ...         ...       ...        ...
964865      6649.74       1022.32  ORD0265813         1      P0076
964866      2181.74       3189.81  ORD0345740         1      P0029
964867     26659.36       3189.81  ORD0345740         4      P0076
964868      4166.56       3570.34  ORD0388198         1      P0063
964869      5447.20        843.92  ORD0412386         1      P0038

[964870 rows x 5 columns]

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df.drop("stock_quantity",axis=1,inplace=True)

In [26]:
df.drop("total_amount",axis=1,inplace = True)

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 964870 entries, 0 to 964869
Data columns (total 25 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   customer_id       964870 non-null  str
 1   full_name         964870 non-null  str
 2   email             964870 non-null  str
 3   city              964870 non-null  str
 4   signup_date       964870 non-null  datetime64[us]
 5   age               964870 non-null  int64
 6   gender            964870 non-null  str
 7   loyalty_tier      964870 non-null  str
 8   order_id          964870 non-null  str
 9   order_date        964870 non-null  datetime64[us]
 10  status            964870 non-null  str
 11  payment_method    964870 non-null  str
 12  delivery_days     964870 non-null  int64
 13  discount_applied  964870 non-null  float64
 14  item_id           964870 non-null  str
 15  product_id        964870 non-null  str
 16  quantity          964870 non-null  int64
 17  unit_price        964870 non-null  float64
 18  total_price       964870 non-null  float64
 19  product_name      964870 non-null  str
 20  category          964870 non-null  str
 21  price             964870 non-null  float64
 22  signup_Month      964870 non-null  str
 23  order_month       964870 non-null  str
 24  order_year        964870 non-null  int32
dtypes: datetime64[us](2), float64(4), int32(1), int64(3), str(15)
memory usage: 180.4 MB

In [43]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:ANUJ%402005@localhost/ANALYS"
)

In [51]:
df.to_sql("sales_data",engine,if_exists='replace',index=False)

964870

In [46]:
df.to_csv(
    r"C:\Users\Anuj\Desktop\sales_data.csv",
    index=False
)

In [49]:
df['gender'] = df['gender'].str.replace("Femaleemale","Female")

In [39]:
df['gender'] = df['gender'].str.replace("M","Male")

In [50]:
df['gender']

0          Male
1          Male
2          Male
3          Male
4          Male
          ...
964865    Other
964866    Other
964867    Other
964868    Other
964869    Other
Name: gender, Length: 964870, dtype: str